       ; SPR 0 @172,40
       MOV @172(R9),R1   ; 55
       MOV R1,R2       ; 54
       AI R2,8
       MOV @174(R9),R3   ; 53
       MOV R3,R4       ; 53
       AI R3,16
       AI R4,24
       MOV @176(R9),R5   ; 52
       MOV R5,R6       ; 51
       AI R5,32
       AI R6,40
       MOV @178(R9),R7   ; 51
       MOV R7,R8       ; 50
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @180(R9),R1   ; 49
       MOV R1,R2       ; 49
       AI R2,8
       MOV @182(R9),R3   ; 48
       MOV R3,R4       ; 48
       AI R3,16
       AI R4,24
       MOV @184(R9),R5   ; 47
       MOV R5,R6       ; 47
       AI R5,32
       AI R6,40
       MOV @186(R9),R7   ; 46
       MOV R7,R8       ; 46
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       MOVB R0,*R15
       ; SPR 1 @188,40
       MOV @188(R9),R1   ; 46
       MOV R1,R2       ; 45
       AI R2,8
       MOV @190(R9),R3   ; 45
       MOV R3,R4       ; 45
       AI R3,16
       AI R4,24
       MOV @192(R9),R5   ; 44
       MOV R5,R6       ; 44
       AI R5,32
       AI R6,40
       MOV @194(R9),R7   ; 44
       MOV R7,R8       ; 44
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       MOV @196(R9),R1   ; 43
       MOV R1,R2       ; 43
       AI R2,8
       MOV @198(R9),R3   ; 43
       MOV R3,R4       ; 43
       AI R3,16
       AI R4,24
       MOV @200(R9),R5   ; 43
       MOV R5,R6       ; 43
       AI R5,32
       AI R6,40
       MOV @202(R9),R7   ; 43
       MOV R7,R8       ; 43
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 2 @204,40
       MOV @204(R9),R1   ; 43
       MOV R1,R2       ; 43
       AI R2,8
       MOV @206(R9),R3   ; 43
       MOV R3,R4       ; 43
       AI R3,16
       AI R4,24
       MOV @208(R9),R5   ; 43
       MOV R5,R6       ; 43
       AI R5,32
       AI R6,40
       MOV @210(R9),R7   ; 43
       MOV R7,R8       ; 44
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @212(R9),R1   ; 44
       MOV R1,R2       ; 44
       AI R2,8
       MOV @214(R9),R3   ; 44
       MOV R3,R4       ; 45
       AI R3,16
       AI R4,24
       MOV @216(R9),R5   ; 45
       MOV R5,R6       ; 45
       AI R5,32
       AI R6,40
       MOV @218(R9),R7   ; 46
       MOV R7,R8       ; 46
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       ; SPR 3 @220,40
       MOV @220(R9),R1   ; 46
       MOV R1,R2       ; 47
       AI R2,8
       MOV @222(R9),R3   ; 47
       MOV R3,R4       ; 48
       AI R3,16
       AI R4,24
       MOV @224(R9),R5   ; 48
       MOV R5,R6       ; 49
       AI R5,32
       AI R6,40
       MOV @226(R9),R7   ; 49
       MOV R7,R8       ; 50
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @228(R9),R1   ; 51
       MOV R1,R2       ; 51
       AI R2,8
       MOV @230(R9),R3   ; 52
       MOV R3,R4       ; 53
       AI R3,16
       AI R4,24
       MOV @232(R9),R5   ; 53
       MOV R5,R6       ; 54
       AI R5,32
       AI R6,40
       MOV @234(R9),R7   ; 55
       MOV R7,R8       ; 56
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       MOVB R0,*R15
       BL @FSYNC
       ; SPR 4 @154,56
       MOV @154(R9),R1   ; 71
       MOV R1,R2       ; 70
       AI R2,8
       MOV @156(R9),R3   ; 69
       MOV R3,R4       ; 68
       AI R3,16
       AI R4,24
       MOV @158(R9),R5   ; 67
       MOV R5,R6       ; 66
       AI R5,32
       AI R6,40
       MOV @160(R9),R7   ; 65
       MOV R7,R8       ; 64
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @162(R9),R1   ; 63
       MOV R1,R2       ; 62
       AI R2,8
       MOV @164(R9),R3   ; 61
       MOV R3,R4       ; 61
       AI R3,16
       AI R4,24
       MOV @166(R9),R5   ; 60
       MOV R5,R6       ; 59
       AI R5,32
       AI R6,40
       MOV @168(R9),R7   ; 58
       MOV R7,R8       ; 57
       AI R7,48
       AI R8,56
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       ; SPR 5 @170,56
       MOV @170(R9),R1   ; 56
       MOV R1,R2       ; 56
       AI R2,8
       MOV @172(R9),R3   ; 55
       MOV R3,R4       ; 54
       AI R3,17
       AI R4,26
       MOV @174(R9),R5   ; 53
       MOV R5,R6       ; 53
       AI R5,35
       AI R6,43
       MOV @176(R9),R7   ; 52
       MOV R7,R8       ; 51
       AI R7,52
       AI R8,61
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @178(R9),R1   ; 51
       MOV R1,R2       ; 50
       AI R1,5
       AI R2,14
       MOV @180(R9),R3   ; 49
       MOV R3,R4       ; 49
       AI R3,23
       AI R4,31
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 6 @224,56
       MOV @224(R9),R1   ; 48
       MOV R1,R2       ; 49
       AI R1,8
       AI R2,15
       MOV @226(R9),R3   ; 49
       MOV R3,R4       ; 50
       AI R3,23
       AI R4,30
       MOV @228(R9),R5   ; 51
       MOV R5,R6       ; 51
       AI R5,37
       AI R6,45
       MOV @230(R9),R7   ; 52
       MOV R7,R8       ; 53
       AI R7,52
       AI R8,59
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @232(R9),R1   ; 53
       MOV R1,R2       ; 54
       AI R1,3
       AI R2,10
       MOV @234(R9),R3   ; 55
       MOV R3,R4       ; 56
       AI R3,17
       AI R4,24
       MOV @236(R9),R5   ; 56
       MOV R5,R6       ; 57
       AI R5,32
       AI R6,40
       MOV @238(R9),R7   ; 58
       MOV R7,R8       ; 59
       AI R7,48
       AI R8,56
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 7 @240,56
       MOV @240(R9),R1   ; 60
       MOV R1,R2       ; 61
       AI R2,8
       MOV @242(R9),R3   ; 61
       MOV R3,R4       ; 62
       AI R3,16
       AI R4,24
       MOV @244(R9),R5   ; 63
       MOV R5,R6       ; 64
       AI R5,32
       AI R6,40
       MOV @246(R9),R7   ; 65
       MOV R7,R8       ; 66
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @248(R9),R1   ; 67
       MOV R1,R2       ; 68
       AI R2,8
       MOV @250(R9),R3   ; 69
       MOV R3,R4       ; 70
       AI R3,16
       AI R4,24
       MOV @252(R9),R5   ; 71
       MOV R5,R6       ; 72
       AI R5,32
       AI R6,40
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       MOVB R0,*R15
       BL @FSYNC
       ; SPR 8 @138,72
       MOV @138(R9),R1   ; 89
       MOV R1,R2       ; 87
       AI R2,8
       MOV @140(R9),R3   ; 86
       MOV R3,R4       ; 85
       AI R3,16
       AI R4,24
       MOV @142(R9),R5   ; 84
       MOV R5,R6       ; 83
       AI R5,32
       AI R6,40
       MOV @144(R9),R7   ; 82
       MOV R7,R8       ; 81
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @146(R9),R1   ; 80
       MOV R1,R2       ; 79
       AI R2,8
       MOV @148(R9),R3   ; 77
       MOV R3,R4       ; 76
       AI R3,16
       AI R4,24
       MOV @150(R9),R5   ; 75
       MOV R5,R6       ; 74
       AI R5,32
       AI R6,40
       MOV @152(R9),R7   ; 73
       MOV R7,R8       ; 72
       AI R7,48
       AI R8,56
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       ; SPR 9 @154,72
       MOV @154(R9),R1   ; 71
       MOV R1,R2       ; 70
       INC R1
       AI R2,10
       MOV @156(R9),R3   ; 69
       MOV R3,R4       ; 68
       AI R3,19
       AI R4,28
       MOV @158(R9),R5   ; 67
       MOV R5,R6       ; 66
       AI R5,37
       AI R6,46
       MOV @160(R9),R7   ; 65
       MOV R7,R8       ; 64
       AI R7,55
       AI R8,64
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 10 @240,72
       MOV @246(R9),R7   ; 65
       MOV R7,R8       ; 66
       AI R7,55
       AI R8,62
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @248(R9),R1   ; 67
       MOV R1,R2       ; 68
       AI R1,5
       AI R2,12
       MOV @250(R9),R3   ; 69
       MOV R3,R4       ; 70
       AI R3,19
       AI R4,26
       MOV @252(R9),R5   ; 71
       MOV R5,R6       ; 72
       AI R5,33
       AI R6,40
       MOV @254(R9),R7   ; 73
       MOV R7,R8       ; 74
       AI R7,48
       AI R8,56
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 11 @256,72
       MOV @256(R9),R1   ; 75
       MOV R1,R2       ; 76
       AI R2,8
       MOV @258(R9),R3   ; 77
       MOV R3,R4       ; 79
       AI R3,16
       AI R4,24
       MOV @260(R9),R5   ; 80
       MOV R5,R6       ; 81
       AI R5,32
       AI R6,40
       MOV @262(R9),R7   ; 82
       MOV R7,R8       ; 83
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @264(R9),R1   ; 84
       MOV R1,R2       ; 85
       AI R2,8
       MOV @266(R9),R3   ; 86
       MOV R3,R4       ; 87
       AI R3,16
       AI R4,24
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       MOVB R0,*R15
       BL @FSYNC
       ; SPR 12 @0,88
       MOV *R9,R1   ; 93
       MOV R1,R2       ; 94
       AI R2,8
       MOV @2(R9),R3   ; 95
       MOV R3,R4       ; 97
       AI R3,16
       AI R4,24
       MOV @4(R9),R5   ; 98
       MOV R5,R6       ; 99
       AI R5,32
       AI R6,40
       MOV @6(R9),R7   ; 100
       MOV R7,R8       ; 101
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @8(R9),R1   ; 102
       MOV R1,R2       ; 103
       AI R2,8
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       MOVB R0,*R15
       ; SPR 13 @124,88
       MOV @124(R9),R1   ; 104
       MOV R1,R2       ; 103
       AI R2,8
       MOV @126(R9),R3   ; 102
       MOV R3,R4       ; 101
       AI R3,16
       AI R4,24
       MOV @128(R9),R5   ; 100
       MOV R5,R6       ; 99
       AI R5,32
       AI R6,40
       MOV @130(R9),R7   ; 98
       MOV R7,R8       ; 97
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @132(R9),R1   ; 95
       MOV R1,R2       ; 94
       AI R2,8
       MOV @134(R9),R3   ; 93
       MOV R3,R4       ; 92
       AI R3,16
       AI R4,24
       MOV @136(R9),R5   ; 91
       MOV R5,R6       ; 90
       AI R5,32
       AI R6,40
       MOV @138(R9),R7   ; 89
       MOV R7,R8       ; 87
       AI R7,48
       AI R8,57
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       ; SPR 14 @140,88
       MOV @140(R9),R1   ; 86
       MOV R1,R2       ; 85
       INCT R1
       AI R2,11
       MOV @142(R9),R3   ; 84
       MOV R3,R4       ; 83
       AI R3,20
       AI R4,29
       MOV @144(R9),R5   ; 82
       MOV R5,R6       ; 81
       AI R5,38
       AI R6,47
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 15 @256,88
       MOV @260(R9),R5   ; 80
       MOV R5,R6       ; 81
       AI R5,40
       AI R6,47
       MOV @262(R9),R7   ; 82
       MOV R7,R8       ; 83
       AI R7,54
       AI R8,61
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @264(R9),R1   ; 84
       MOV R1,R2       ; 85
       AI R1,4
       AI R2,11
       MOV @266(R9),R3   ; 86
       MOV R3,R4       ; 87
       AI R3,18
       AI R4,25
       MOV @268(R9),R5   ; 89
       MOV R5,R6       ; 90
       AI R5,32
       AI R6,40
       MOV @270(R9),R7   ; 91
       MOV R7,R8       ; 92
       AI R7,48
       AI R8,56
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       BL @FSYNC
       ; SPR 16 @0,104
       MOV @2(R9),R3   ; 95
       MOV R3,R4       ; 97
       AI R3,25
       AI R4,31
       MOV @4(R9),R5   ; 98
       MOV R5,R6       ; 99
       AI R5,38
       AI R6,45
       MOV @6(R9),R7   ; 100
       MOV R7,R8       ; 101
       AI R7,52
       AI R8,59
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @8(R9),R1   ; 102
       MOV R1,R2       ; 103
       INCT R1
       AI R2,9
       MOV @10(R9),R3   ; 104
       MOV R3,R4       ; 105
       AI R3,16
       AI R4,24
       MOV @12(R9),R5   ; 107
       MOV R5,R6       ; 108
       AI R5,32
       AI R6,40
       MOV @14(R9),R7   ; 109
       MOV R7,R8       ; 110
       AI R7,48
       AI R8,56
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       ; SPR 17 @16,104
       MOV @16(R9),R1   ; 111
       MOV R1,R2       ; 112
       AI R2,8
       MOV @18(R9),R3   ; 113
       MOV R3,R4       ; 114
       AI R3,16
       AI R4,24
       MOV @20(R9),R5   ; 115
       MOV R5,R6       ; 116
       AI R5,32
       AI R6,40
       MOV @22(R9),R7   ; 117
       MOV R7,R8       ; 118
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @24(R9),R1   ; 119
       MOV R1,R2       ; 120
       AI R2,8
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1,*R15
       ; SPR 18 @110,104
       MOV @110(R9),R1   ; 119
       MOV R1,R2       ; 118
       AI R2,8
       MOV @112(R9),R3   ; 117
       MOV R3,R4       ; 116
       AI R3,16
       AI R4,24
       MOV @114(R9),R5   ; 115
       MOV R5,R6       ; 114
       AI R5,32
       AI R6,40
       MOV @116(R9),R7   ; 113
       MOV R7,R8       ; 112
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @118(R9),R1   ; 111
       MOV R1,R2       ; 110
       AI R2,8
       MOV @120(R9),R3   ; 109
       MOV R3,R4       ; 108
       AI R3,16
       AI R4,24
       MOV @122(R9),R5   ; 107
       MOV R5,R6       ; 105
       AI R5,32
       AI R6,40
       MOV @124(R9),R7   ; 104
       MOV R7,R8       ; 103
       AI R7,48
       AI R8,57
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       ; SPR 19 @126,104
       MOV @126(R9),R1   ; 102
       MOV R1,R2       ; 101
       INCT R1
       AI R2,11
       MOV @128(R9),R3   ; 100
       MOV R3,R4       ; 99
       AI R3,20
       AI R4,29
       MOV @130(R9),R5   ; 98
       MOV R5,R6       ; 97
       AI R5,38
       AI R6,47
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       BL @FSYNC
       ; SPR 20 @18,120
       MOV @18(R9),R1   ; 113
       MOV R1,R2       ; 114
       AI R1,7
       AI R2,14
       MOV @20(R9),R3   ; 115
       MOV R3,R4       ; 116
       AI R3,21
       AI R4,28
       MOV @22(R9),R5   ; 117
       MOV R5,R6       ; 118
       AI R5,35
       AI R6,42
       MOV @24(R9),R7   ; 119
       MOV R7,R8       ; 120
       AI R7,49
       AI R8,56
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @26(R9),R1   ; 121
       MOV R1,R2       ; 122
       AI R2,8
       MOV @28(R9),R3   ; 123
       MOV R3,R4       ; 123
       AI R3,16
       AI R4,24
       MOV @30(R9),R5   ; 124
       MOV R5,R6       ; 125
       AI R5,32
       AI R6,40
       MOV @32(R9),R7   ; 126
       MOV R7,R8       ; 127
       AI R7,48
       AI R8,56
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       ; SPR 21 @34,120
       MOV @34(R9),R1   ; 128
       MOV R1,R2       ; 128
       AI R2,8
       MOV @36(R9),R3   ; 129
       MOV R3,R4       ; 130
       AI R3,16
       AI R4,24
       MOV @38(R9),R5   ; 131
       MOV R5,R6       ; 131
       AI R5,32
       AI R6,40
       MOV @40(R9),R7   ; 132
       MOV R7,R8       ; 133
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @42(R9),R1   ; 133
       MOV R1,R2       ; 134
       AI R2,8
       MOV @44(R9),R3   ; 135
       MOV R3,R4       ; 135
       AI R3,16
       AI R4,24
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       MOVB R0,*R15
       ; SPR 22 @88,120
       MOV @88(R9),R1   ; 136
       MOV R1,R2       ; 135
       AI R2,8
       MOV @90(R9),R3   ; 135
       MOV R3,R4       ; 134
       AI R3,16
       AI R4,24
       MOV @92(R9),R5   ; 133
       MOV R5,R6       ; 133
       AI R5,32
       AI R6,40
       MOV @94(R9),R7   ; 132
       MOV R7,R8       ; 131
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOV @96(R9),R1   ; 131
       MOV R1,R2       ; 130
       AI R2,8
       MOV @98(R9),R3   ; 129
       MOV R3,R4       ; 128
       AI R3,16
       AI R4,24
       MOV @100(R9),R5   ; 128
       MOV R5,R6       ; 127
       AI R5,32
       AI R6,40
       MOV @102(R9),R7   ; 126
       MOV R7,R8       ; 125
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       MOVB R0,*R15
       ; SPR 23 @104,120
       MOV @104(R9),R1   ; 124
       MOV R1,R2       ; 123
       AI R2,8
       MOV @106(R9),R3   ; 123
       MOV R3,R4       ; 122
       AI R3,16
       AI R4,24
       MOV @108(R9),R5   ; 121
       MOV R5,R6       ; 120
       AI R5,32
       AI R6,40
       MOV @110(R9),R7   ; 119
       MOV R7,R8       ; 118
       AI R7,49
       AI R8,58
       MOVB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @112(R9),R1   ; 117
       MOV R1,R2       ; 116
       AI R1,3
       AI R2,12
       MOV @114(R9),R3   ; 115
       MOV R3,R4       ; 114
       AI R3,21
       AI R4,30
       MOV @116(R9),R5   ; 113
       MOV R5,R6       ; 112
       AI R5,39
       AI R6,48
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       BL @FSYNC
       ; SPR 24 @36,136
       MOV @36(R9),R1   ; 129
       MOV R1,R2       ; 130
       AI R1,7
       AI R2,14
       MOV @38(R9),R3   ; 131
       MOV R3,R4       ; 131
       AI R3,21
       AI R4,29
       MOV @40(R9),R5   ; 132
       MOV R5,R6       ; 133
       AI R5,36
       AI R6,43
       MOV @42(R9),R7   ; 133
       MOV R7,R8       ; 134
       AI R7,51
       AI R8,58
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R6,R0
       SOCB *R7,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R8,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @44(R9),R1   ; 135
       MOV R1,R2       ; 135
       INC R1
       AI R2,9
       MOV @46(R9),R3   ; 136
       MOV R3,R4       ; 136
       AI R3,16
       AI R4,24
       MOV @48(R9),R5   ; 137
       MOV R5,R6       ; 137
       AI R5,32
       AI R6,40
       MOV @50(R9),R7   ; 138
       MOV R7,R8       ; 138
       AI R7,48
       AI R8,56
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R3,R0
       SOCB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 25 @52,136
       MOV @52(R9),R1   ; 138
       MOV R1,R2       ; 139
       AI R2,8
       MOV @54(R9),R3   ; 139
       MOV R3,R4       ; 139
       AI R3,16
       AI R4,24
       MOV @56(R9),R5   ; 140
       MOV R5,R6       ; 140
       AI R5,32
       AI R6,40
       MOV @58(R9),R7   ; 140
       MOV R7,R8       ; 140
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       MOVB *R1+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @60(R9),R1   ; 141
       MOV R1,R2       ; 141
       AI R2,8
       MOV @62(R9),R3   ; 141
       MOV R3,R4       ; 141
       AI R3,16
       AI R4,24
       MOV @64(R9),R5   ; 141
       MOV R5,R6       ; 141
       AI R5,32
       AI R6,40
       MOV @66(R9),R7   ; 141
       MOV R7,R8       ; 141
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 26 @68,136
       MOV @68(R9),R1   ; 141
       MOV R1,R2       ; 141
       AI R2,8
       MOV @70(R9),R3   ; 141
       MOV R3,R4       ; 141
       AI R3,16
       AI R4,24
       MOV @72(R9),R5   ; 141
       MOV R5,R6       ; 141
       AI R5,32
       AI R6,40
       MOV @74(R9),R7   ; 141
       MOV R7,R8       ; 140
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOVB *R8+,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       SOCB *R7,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @76(R9),R1   ; 140
       MOV R1,R2       ; 140
       AI R2,8
       MOV @78(R9),R3   ; 140
       MOV R3,R4       ; 139
       AI R3,16
       AI R4,24
       MOV @80(R9),R5   ; 139
       MOV R5,R6       ; 139
       AI R5,32
       AI R6,40
       MOV @82(R9),R7   ; 138
       MOV R7,R8       ; 138
       AI R7,48
       AI R8,56
       CLR *R15
       CLR *R15
       MOVB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       SOCB *R5,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       SOCB *R3,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       ; SPR 27 @84,136
       MOV @84(R9),R1   ; 138
       MOV R1,R2       ; 137
       AI R2,8
       MOV @86(R9),R3   ; 137
       MOV R3,R4       ; 136
       AI R3,16
       AI R4,24
       MOV @88(R9),R5   ; 136
       MOV R5,R6       ; 135
       AI R5,32
       AI R6,41
       MOV @90(R9),R7   ; 135
       MOV R7,R8       ; 134
       AI R7,49
       AI R8,58
       MOVB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8+,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7+,R0
       SOCB *R8,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       MOV @92(R9),R1   ; 133
       MOV R1,R2       ; 133
       AI R1,3
       AI R2,11
       MOV @94(R9),R3   ; 132
       MOV R3,R4       ; 131
       AI R3,20
       AI R4,29
       MOV @96(R9),R5   ; 131
       MOV R5,R6       ; 130
       AI R5,37
       AI R6,46
       MOV @98(R9),R7   ; 129
       MOV R7,R8       ; 128
       AI R7,55
       AI R8,64
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6+,R0
       SOCB *R7,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4+,R0
       SOCB *R5+,R0
       SOCB *R6,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3+,R0
       SOCB *R4,R0
       SOCB *R5,R0
       MOVB R0,*R15
       MOVB *R1+,R0
       SOCB *R2+,R0
       SOCB *R3,R0
       MOVB R0,*R15
       MOVB *R1,R0
       SOCB *R2,R0
       MOVB R0,*R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       CLR *R15
       BL @FSYNC
       B @RUNSRT
SPRDATA
       DATA >2800,>AC05 ; 172,40  
       DATA >2804,>BC05 ; 188,40  
       DATA >2808,>CC05 ; 204,40  
       DATA >280C,>DC05 ; 220,40  
       DATA >3810,>9A05 ; 154,56  
       DATA >3814,>AA05 ; 170,56  
       DATA >3818,>E005 ; 224,56  
       DATA >381C,>F005 ; 240,56  
       DATA >4820,>8A05 ; 138,72  
       DATA >4824,>9A05 ; 154,72  
       DATA >4828,>F005 ; 240,72  
       DATA >482C,>1085 ; 256,72  
       DATA >5830,>0005 ; 0,88  
       DATA >5834,>7C05 ; 124,88  
       DATA >5838,>8C05 ; 140,88  
       DATA >583C,>1085 ; 256,88  
       DATA >6840,>0005 ; 0,104  
       DATA >6844,>1005 ; 16,104  
       DATA >6848,>6E05 ; 110,104  
       DATA >684C,>7E05 ; 126,104  
       DATA >7850,>1205 ; 18,120  
       DATA >7854,>2205 ; 34,120  
       DATA >7858,>5805 ; 88,120  
       DATA >785C,>6805 ; 104,120  
       DATA >8860,>2405 ; 36,136  
       DATA >8864,>3405 ; 52,136  
       DATA >8868,>4405 ; 68,136  
       DATA >886C,>5405 ; 84,136  
